# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.1.dev1+g0fe4806.d20221009'
__version_tuple__ = version_tuple = (0, 1, 1, 'dev1', 'g0fe4806.d20221009')
